version: '3.7'

networks:
  golang-restful-api:
    name: golang-restful-api

services:
  mysql:
    container_name: golang-restful-api-mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
    networks:
      - golang-restful-api
